### ISSUE TITLE
单个类别病害的map值

### ISSUE THREAD

**Issue by jiaerfei** [hzlbbfrog/CenWholeNet#1]
同学你好，有幸拜读了你发在《Automation in Construction》上的文章“Automatic damage detection using anchor-free method and unmanned surface vessel ”，受益匪浅，非常好的一篇文章。
这里有一个问题想要咨询一下你：请问你是如何获得针对每一类病害的map值的？

**Comment by hzlbbfrog** [comment]
朋友你好，每一类病害的map你可以在cocoapi里面修改，让它输出每类的map。
我是因为病害数据集里面，拍的病害没有一张图片有两种病害的，所以我只需要对测试集每类病害的所有图片单独测试就行了。
Thank you for your attention！
Have a nice weekend～

**Comment by jiaerfei** [comment]
好的，谢谢，我之后尝试一下。
